/**
 * Lookup table CID-10 → Descrição em Português
 * Cobre todos os CIDs presentes nos 243 protocolos + comuns na prática clínica.
 */

export interface CIDInfo {
    description: string;
    category: string;
}

export const CID10_LOOKUP: Record<string, CIDInfo> = {
    // ── Aparelho Respiratório ──
    'J00': { description: 'Nasofaringite aguda (resfriado comum)', category: 'Respiratório' },
    'J02.9': { description: 'Faringoamigdalite aguda não especificada', category: 'Respiratório' },
    'J03.9': { description: 'Amigdalite aguda não especificada', category: 'Respiratório' },
    'J04.0': { description: 'Laringite aguda', category: 'Respiratório' },
    'J04.2': { description: 'Laringotraqueíte aguda (Crupe)', category: 'Respiratório' },
    'J06.9': { description: 'Infecção aguda das vias aéreas superiores não especificada', category: 'Respiratório' },
    'J18.9': { description: 'Pneumonia não especificada', category: 'Respiratório' },
    'J20.9': { description: 'Bronquite aguda não especificada', category: 'Respiratório' },
    'J21.0': { description: 'Bronquiolite aguda por vírus sincicial respiratório', category: 'Respiratório' },
    'J21.9': { description: 'Bronquiolite aguda não especificada', category: 'Respiratório' },
    'J30.1': { description: 'Rinite alérgica devida a pólen', category: 'Respiratório' },
    'J30.4': { description: 'Rinite alérgica não especificada', category: 'Respiratório' },
    'J32.9': { description: 'Sinusite crônica não especificada', category: 'Respiratório' },
    'J38.5': { description: 'Laringospasmo (Laringite Estridulosa)', category: 'Respiratório' },
    'J44.0': { description: 'DPOC com infecção respiratória aguda', category: 'Respiratório' },
    'J44.1': { description: 'DPOC com exacerbação aguda', category: 'Respiratório' },
    'J45.9': { description: 'Asma não especificada', category: 'Respiratório' },
    'J46': { description: 'Estado de mal asmático (Crise de Asma)', category: 'Respiratório' },
    'J01.9': { description: 'Rinossinusite aguda não especificada', category: 'Respiratório' },
    'J15.9': { description: 'Pneumonia bacteriana não especificada', category: 'Respiratório' },

    // ── Aparelho Circulatório / Cardiologia ──
    'I10': { description: 'Hipertensão arterial essencial (primária)', category: 'Cardiologia' },
    'I16.0': { description: 'Urgência hipertensiva', category: 'Cardiologia' },
    'I16.1': { description: 'Emergência hipertensiva', category: 'Cardiologia' },
    'I21.9': { description: 'Infarto agudo do miocárdio não especificado (IAM)', category: 'Cardiologia' },
    'I50.9': { description: 'Insuficiência cardíaca não especificada', category: 'Cardiologia' },
    'I63.9': { description: 'AVC isquêmico não especificado', category: 'Cardiologia' },
    'I80.2': { description: 'Tromboflebite de vasos profundos dos membros inferiores (TVP)', category: 'Cardiologia' },
    'I83.0': { description: 'Varizes dos membros inferiores com úlcera', category: 'Cardiologia' },
    'I83.9': { description: 'Varizes dos membros inferiores sem úlcera ou inflamação', category: 'Cardiologia' },
    'I87.2': { description: 'Insuficiência venosa crônica', category: 'Cardiologia' },
    'I95.1': { description: 'Hipotensão ortostática', category: 'Cardiologia' },
    'I70.2': { description: 'Aterosclerose das artérias dos membros (claudicação)', category: 'Cardiologia' },
    'R00.0': { description: 'Taquicardia não especificada', category: 'Cardiologia' },
    'R55': { description: 'Síncope e colapso (desmaio)', category: 'Cardiologia' },

    // ── Aparelho Digestivo ──
    'K21.0': { description: 'Doença do refluxo gastroesofágico com esofagite (DRGE)', category: 'Digestivo' },
    'K21.9': { description: 'Doença do refluxo gastroesofágico sem esofagite', category: 'Digestivo' },
    'K25.9': { description: 'Úlcera gástrica não especificada', category: 'Digestivo' },
    'K29.7': { description: 'Gastrite não especificada (Dispepsia)', category: 'Digestivo' },
    'K37': { description: 'Apendicite não especificada', category: 'Digestivo' },
    'K40.9': { description: 'Hérnia inguinal unilateral, sem obstrução', category: 'Digestivo' },
    'K40.3': { description: 'Hérnia inguinal com obstrução (Encarcerada)', category: 'Digestivo' },
    'K42.9': { description: 'Hérnia umbilical sem obstrução', category: 'Digestivo' },
    'K52.9': { description: 'Gastroenterite não infecciosa não especificada', category: 'Digestivo' },
    'K57.30': { description: 'Doença diverticular sem perfuração', category: 'Digestivo' },
    'K58.9': { description: 'Síndrome do intestino irritável sem diarreia', category: 'Digestivo' },
    'K59.0': { description: 'Constipação intestinal', category: 'Digestivo' },
    'K62.5': { description: 'Hemorragia do ânus e do reto (Hemorroida)', category: 'Digestivo' },
    'K64.9': { description: 'Doença hemorroidária não especificada', category: 'Digestivo' },
    'K70.0': { description: 'Fígado gorduroso alcoólico (Esteatose)', category: 'Digestivo' },
    'K76.0': { description: 'Fígado gordo não classificado em outra parte (NAFLD)', category: 'Digestivo' },
    'K80.2': { description: 'Colelitíase com colecistite aguda', category: 'Digestivo' },
    'K80.5': { description: 'Colelitíase sem colecistite (Cálculo biliar)', category: 'Digestivo' },
    'K90.0': { description: 'Doença celíaca', category: 'Digestivo' },
    'K91.1': { description: 'Vômitos após cirurgia gastrointestinal', category: 'Digestivo' },
    'K92.1': { description: 'Melena (Hemorragia Digestiva Alta)', category: 'Digestivo' },
    'K92.0': { description: 'Hematêmese (vômito com sangue)', category: 'Digestivo' },
    'K12.0': { description: 'Aftas recorrentes da mucosa oral (Estomatite Aftosa)', category: 'Digestivo' },
    'K51.9': { description: 'Colite ulcerativa não especificada', category: 'Digestivo' },
    'K50.9': { description: 'Doença de Crohn não especificada', category: 'Digestivo' },

    // ── Aparelho Geniturinário ──
    'N20.0': { description: 'Cálculo renal / pedra nos rins', category: 'Urologia' },
    'N23': { description: 'Cólica nefrética não especificada', category: 'Urologia' },
    'N30.0': { description: 'Cistite aguda', category: 'Urologia' },
    'N39.0': { description: 'Infecção do trato urinário de localização não especificada', category: 'Urologia' },
    'N40': { description: 'Hiperplasia da próstata (HPB)', category: 'Urologia' },
    'N45': { description: 'Orquite e epididimite (Orquiepididimite)', category: 'Urologia' },
    'N50.1': { description: 'Varicocele', category: 'Urologia' },
    'N53.1': { description: 'Disfunção erétil', category: 'Urologia' },
    'N53.9': { description: 'Disfunção sexual masculina não especificada', category: 'Urologia' },
    'N81.1': { description: 'Cistocele / Incontinência urinária', category: 'Urologia' },
    'R33': { description: 'Retenção urinária', category: 'Urologia' },
    'N10': { description: 'Pielonefrite tubulointersticial aguda', category: 'Urologia' },
    'N41.0': { description: 'Prostatite aguda (ITU Masculina)', category: 'Urologia' },
    'N34.1': { description: 'Uretrite não especificada', category: 'Urologia' },
    'N76.0': { description: 'Vaginite aguda', category: 'Ginecologia' },
    'N76.1': { description: 'Vaginite subaguda e crônica (Vaginose)', category: 'Ginecologia' },
    'N53.12': { description: 'Disfunção erétil', category: 'Urologia' },
    'N43.3': { description: 'Hidrocele não especificada', category: 'Urologia' },
    'Q53.9': { description: 'Testículo não descido não especificado (Criptorquidia)', category: 'Urologia' },
    'N47': { description: 'Fimose e parafimose', category: 'Urologia' },
    'N48.6': { description: 'Balanopostite', category: 'Urologia' },
    'N32.8': { description: 'Outras afecções especificadas da bexiga (Bexiga hiperativa)', category: 'Urologia' },

    // ── Ginecologia / Obstetrícia ──
    'A59.0': { description: 'Tricomoníase urogenital', category: 'Ginecologia' },
    'B37.3': { description: 'Candidíase vulvovaginal', category: 'Ginecologia' },
    'N91.2': { description: 'Amenorreia não especificada', category: 'Ginecologia' },
    'N94.3': { description: 'Síndrome pré-menstrual (TPM)', category: 'Ginecologia' },
    'N94.4': { description: 'Dismenorreia primária', category: 'Ginecologia' },
    'N94.5': { description: 'Dismenorreia secundária', category: 'Ginecologia' },
    'N73.9': { description: 'Doença inflamatória pélvica não especificada (DIP)', category: 'Ginecologia' },
    'N80.9': { description: 'Endometriose não especificada', category: 'Ginecologia' },
    'N83.2': { description: 'Cisto do ovário não especificado', category: 'Ginecologia' },
    'N92.0': { description: 'Sangramento uterino anormal (SUA)', category: 'Ginecologia' },
    'N95.1': { description: 'Menopausa e climatério', category: 'Ginecologia' },
    'N95.3': { description: 'Vaginite atrófica pós-menopáusica', category: 'Ginecologia' },
    'N97.9': { description: 'Infertilidade feminina não especificada', category: 'Ginecologia' },
    'O00.9': { description: 'Gravidez ectópica não especificada', category: 'Obstetrícia' },
    'O20.0': { description: 'Ameaça de aborto (sangramento 1º trimestre)', category: 'Obstetrícia' },
    'O26.7': { description: 'Distúrbios da bola e do ligamento redondo na gravidez', category: 'Obstetrícia' },
    'O62.0': { description: 'Contrações primárias inadequadas', category: 'Obstetrícia' },
    'O21.0': { description: 'Hiperemese gravídica leve', category: 'Obstetrícia' },
    'O14.1': { description: 'Pré-eclâmpsia grave', category: 'Obstetrícia' },
    'O60.2': { description: 'Parto prematuro com trabalho de parto prematuro', category: 'Obstetrícia' },
    'N71.0': { description: 'Doença inflamatória aguda do útero (Mastite)', category: 'Ginecologia' },
    'O91.2': { description: 'Mastite puerperal', category: 'Obstetrícia' },
    'N64.3': { description: 'Galactorreia', category: 'Ginecologia' },
    'N63': { description: 'Nódulo mamário não especificado', category: 'Ginecologia' },
    'E28.2': { description: 'Síndrome dos ovários policísticos (SOP)', category: 'Ginecologia' },
    'N90.3': { description: 'Displasia vulvar (Sinéquia de pequenos lábios)', category: 'Ginecologia' },
    'N89.6': { description: 'Estreitamento e estenose vaginal', category: 'Ginecologia' },
    'O99.8': { description: 'Outras doenças maternas que complicam a gravidez', category: 'Obstetrícia' },

    // ── Endocrinologia ──
    'E10.1': { description: 'Diabetes mellitus tipo 1 com cetoacidose (CAD)', category: 'Endocrinologia' },
    'E10.4': { description: 'Diabetes tipo 1 com complicações neurológicas (Neuropatia)', category: 'Endocrinologia' },
    'E11.4': { description: 'Diabetes tipo 2 com complicações neurológicas (Neuropatia)', category: 'Endocrinologia' },
    'E11.9': { description: 'Diabetes mellitus tipo 2 sem complicações', category: 'Endocrinologia' },
    'E14.4': { description: 'Diabetes mellitus não especificado com complicações neurológicas', category: 'Endocrinologia' },
    'E16.0': { description: 'Hipoglicemia induzida por insulina', category: 'Endocrinologia' },
    'E16.2': { description: 'Hipoglicemia não especificada', category: 'Endocrinologia' },
    'E03.9': { description: 'Hipotireoidismo não especificado', category: 'Endocrinologia' },
    'E05.9': { description: 'Tireotoxicose (Hipertireoidismo) não especificada', category: 'Endocrinologia' },
    'E11.649': { description: 'Diabetes tipo 2 com hipoglicemia', category: 'Endocrinologia' },
    'E55.9': { description: 'Deficiência de vitamina D não especificada', category: 'Endocrinologia' },
    'E53.8': { description: 'Deficiência de outras vitaminas B especificadas (B12)', category: 'Endocrinologia' },
    'E78.5': { description: 'Hiperlipidemia não especificada (Dislipidemia)', category: 'Endocrinologia' },
    'E66.9': { description: 'Obesidade não especificada', category: 'Endocrinologia' },
    'E22.1': { description: 'Hiperprolactinemia', category: 'Endocrinologia' },
    'M81.0': { description: 'Osteoporose senil', category: 'Endocrinologia' },

    // ── Dermatologia ──
    'L00': { description: 'Síndrome da pele escaldada estafilocócica', category: 'Dermatologia' },
    'L01.0': { description: 'Impetigo (infecção cutânea estafilocócica)', category: 'Dermatologia' },
    'L03.0': { description: 'Celulite de dedo de mão e pé (Paroníquia)', category: 'Dermatologia' },
    'L03.1': { description: 'Celulite do membro', category: 'Dermatologia' },
    'L03.9': { description: 'Celulite não especificada', category: 'Dermatologia' },
    'L08.0': { description: 'Piodermite (Impetigo, furúnculo)', category: 'Dermatologia' },
    'L20.9': { description: 'Dermatite atópica não especificada', category: 'Dermatologia' },
    'L21.9': { description: 'Dermatite seborreica não especificada (caspa)', category: 'Dermatologia' },
    'L22': { description: 'Dermatite das fraldas (assadura)', category: 'Dermatologia' },
    'L23.9': { description: 'Dermatite de contato alérgica não especificada', category: 'Dermatologia' },
    'L25.9': { description: 'Dermatite de contato não especificada', category: 'Dermatologia' },
    'L27.1': { description: 'Erupção cutânea localizada devida a drogas e medicamentos (Farmacodermia)', category: 'Dermatologia' },
    'L29.9': { description: 'Prurido não especificado (Prurido Anal)', category: 'Dermatologia' },
    'L30.9': { description: 'Dermatite não especificada (Intertrigo)', category: 'Dermatologia' },
    'L40.0': { description: 'Psoríase vulgar', category: 'Dermatologia' },
    'L41.0': { description: 'Pitiríase liquenoide e varioliforme aguda', category: 'Dermatologia' },
    'L42': { description: 'Pitiríase rósea', category: 'Dermatologia' },
    'L43.9': { description: 'Líquen plano não especificado', category: 'Dermatologia' },
    'L50.9': { description: 'Urticária não especificada (Urticária aguda)', category: 'Dermatologia' },
    'L51.9': { description: 'Eritema multiforme não especificado', category: 'Dermatologia' },
    'L57.0': { description: 'Ceratose actínica', category: 'Dermatologia' },
    'L60.0': { description: 'Onicocriptose (Unha encravada)', category: 'Dermatologia' },
    'L71.9': { description: 'Rosácea não especificada', category: 'Dermatologia' },
    'L72.0': { description: 'Cisto epidérmico (cisto sebáceo)', category: 'Dermatologia' },
    'L73.9': { description: 'Foliculite não especificada (Pseudofoliculite)', category: 'Dermatologia' },
    'L80': { description: 'Vitiligo', category: 'Dermatologia' },
    'L81.1': { description: 'Melasma', category: 'Dermatologia' },
    'L82': { description: 'Queratose seborreica', category: 'Dermatologia' },
    'L90.5': { description: 'Cicatriz fibrosa / queloide / cicatriz hipertrófica', category: 'Dermatologia' },
    'L92.9': { description: 'Granuloma da pele não especificado', category: 'Dermatologia' },
    'L98.9': { description: 'Afecção da pele e do tecido subcutâneo não especificada', category: 'Dermatologia' },
    'L63.9': { description: 'Alopecia areata não especificada', category: 'Dermatologia' },
    'L65.9': { description: 'Queda de cabelo não cicatricial não especificada', category: 'Dermatologia' },
    'L30.4': { description: 'Eritema intertrigo', category: 'Dermatologia' },
    'L70.0': { description: 'Acne vulgar', category: 'Dermatologia' },
    'L85.2': { description: 'Calos e calosidades', category: 'Dermatologia' },
    'L74.0': { description: 'Miliária cristalina (Brotoeja)', category: 'Dermatologia' },
    'L74.3': { description: 'Miliária não especificada', category: 'Dermatologia' },
    'L91.0': { description: 'Queloide', category: 'Dermatologia' },
    'L98.4': { description: 'Úlcera cutânea crônica não especificada (Pé diabético)', category: 'Dermatologia' },

    // ── Infectologia ──
    'A00.9': { description: 'Cólera não especificada (Gastroenterite)', category: 'Infectologia' },
    'A02.0': { description: 'Enterite por Salmonella', category: 'Infectologia' },
    'A09': { description: 'Outras gastroenterites e colites de origem infecciosa e NE', category: 'Infectologia' },
    'A30.9': { description: 'Hanseníase não especificada', category: 'Infectologia' },
    'A41.9': { description: 'Septicemia não especificada (Sepse)', category: 'Infectologia' },
    'A51.0': { description: 'Sífilis genital primária', category: 'Infectologia' },
    'A51.3': { description: 'Sífilis secundária da pele e mucosas', category: 'Infectologia' },
    'A51.9': { description: 'Sífilis precoce não especificada', category: 'Infectologia' },
    'A60.9': { description: 'Infecção anogenital por vírus do Herpes', category: 'Infectologia' },
    'A75.9': { description: 'Tifo não especificado', category: 'Infectologia' },
    'A77.0': { description: 'Febre maculosa por Rickettsia rickettsii', category: 'Infectologia' },
    'A87.9': { description: 'Meningite viral não especificada', category: 'Infectologia' },
    'A90': { description: 'Dengue', category: 'Infectologia' },
    'B00.1': { description: 'Herpes simples labial (Herpesviral)', category: 'Infectologia' },
    'B00.2': { description: 'Gengivostomatite herpética', category: 'Infectologia' },
    'B01.9': { description: 'Varicela sem complicação (Catapora)', category: 'Infectologia' },
    'B02.3': { description: 'Herpes zoster com complicações oculares (Oftálmico)', category: 'Infectologia' },
    'B02.9': { description: 'Herpes zoster não especificado (Cobreiro)', category: 'Infectologia' },
    'B08.4': { description: 'Estomatite vesicular com exantema (Mão-pé-boca)', category: 'Infectologia' },
    'B26.9': { description: 'Parotidite infecciosa não especificada (Caxumba)', category: 'Infectologia' },
    'B27.9': { description: 'Mononucleose infecciosa não especificada', category: 'Infectologia' },
    'B35.0': { description: 'Tinha da barba e do couro cabeludo (Tinea capitis)', category: 'Infectologia' },
    'B35.4': { description: 'Tinha do corpo (Tinea corporis)', category: 'Infectologia' },
    'B35.3': { description: 'Tinha da mão', category: 'Infectologia' },
    'B35.1': { description: 'Tinha não especificada', category: 'Infectologia' },
    'B35.6': { description: 'Tinha da virilha (Tinea cruris)', category: 'Infectologia' },
    'B36.0': { description: 'Pitiríase versicolor (Pano branco)', category: 'Infectologia' },
    'B37.0': { description: 'Estomatite por Candida (Sapinho)', category: 'Infectologia' },
    'B35.2': { description: 'Tinha do pé (Tinea pedis / Frieira)', category: 'Infectologia' },
    'B07': { description: 'Verrugas virais', category: 'Infectologia' },
    'B08.1': { description: 'Molusco contagioso', category: 'Infectologia' },
    'B85.2': { description: 'Pediculose não especificada (Piolho)', category: 'Infectologia' },
    'B86': { description: 'Escabiose (Sarna)', category: 'Infectologia' },
    'B99': { description: 'Doença infecciosa não especificada', category: 'Infectologia' },
    'T63.2': { description: 'Efeito tóxico de veneno de escorpião', category: 'Infectologia' },
    'T63.3': { description: 'Efeito tóxico de veneno de aranha', category: 'Infectologia' },

    // ── Neurologia / Psiquiatria ──
    'F32.1': { description: 'Episódio depressivo moderado', category: 'Psiquiatria' },
    'F32.9': { description: 'Episódio depressivo não especificado', category: 'Psiquiatria' },
    'F41.0': { description: 'Transtorno de pânico (Crise de ansiedade)', category: 'Psiquiatria' },
    'F41.9': { description: 'Transtorno ansioso não especificado', category: 'Psiquiatria' },
    'F45.4': { description: 'Transtorno doloroso somatoforme persistente', category: 'Psiquiatria' },
    'F51.0': { description: 'Insônia não orgânica', category: 'Psiquiatria' },
    'F51.4': { description: 'Terrores noturnos', category: 'Psiquiatria' },
    'F17.2': { description: 'Tabagismo / Dependência de nicotina', category: 'Psiquiatria' },
    'F45.3': { description: 'Disfunção autonômica somatoforme', category: 'Psiquiatria' },
    'G20': { description: 'Doença de Parkinson', category: 'Neurologia' },
    'G25.0': { description: 'Tremor essencial', category: 'Neurologia' },
    'G25.3': { description: 'Mioclonia', category: 'Neurologia' },
    'G35': { description: 'Esclerose múltipla', category: 'Neurologia' },
    'G40.9': { description: 'Epilepsia não especificada (Crise convulsiva)', category: 'Neurologia' },
    'G43.9': { description: 'Enxaqueca não especificada', category: 'Neurologia' },
    'G44.2': { description: 'Cefaleia tensional', category: 'Neurologia' },
    'G51.0': { description: 'Paralisia de Bell (Paralisia facial periférica)', category: 'Neurologia' },
    'G54.2': { description: 'Lesão de raízes nervo cervical (Cervicalgia)', category: 'Neurologia' },
    'G54.9': { description: 'Afecção das raízes e plexos nervosos NE (Ciatalgia)', category: 'Neurologia' },
    'G56.0': { description: 'Síndrome do túnel do carpo', category: 'Neurologia' },
    'G57.0': { description: 'Lesão do nervo ciático (Ciatalgia)', category: 'Neurologia' },
    'G59.0': { description: 'Mononeurite do membro inferior (Neuropatia diabetes)', category: 'Neurologia' },
    'G63.2': { description: 'Polineuropatia diabética', category: 'Neurologia' },
    'G50.0': { description: 'Neuralgia do trigêmeo', category: 'Neurologia' },

    // ── Musculoesquelético / Ortopedia ──
    'M06.9': { description: 'Artrite reumatoide não especificada', category: 'Reumatologia' },
    'M10.9': { description: 'Gota não especificada (Artrite gotosa aguda)', category: 'Reumatologia' },
    'M15.9': { description: 'Poliartrose não especificada (Artrose)', category: 'Ortopedia' },
    'M17.1': { description: 'Gonartrose primária (Osteoartrite do joelho)', category: 'Ortopedia' },
    'M19.9': { description: 'Artrose não especificada', category: 'Ortopedia' },
    'M20.1': { description: 'Hálux valgo (Joanete)', category: 'Ortopedia' },
    'M21.4': { description: 'Pé plano', category: 'Ortopedia' },
    'M25.5': { description: 'Dor articular não especificada', category: 'Ortopedia' },
    'M35.0': { description: 'Síndrome de Sjögren', category: 'Reumatologia' },
    'M41.9': { description: 'Escoliose não especificada', category: 'Ortopedia' },
    'M47.8': { description: 'Espondilose com radiculopatia cervical', category: 'Ortopedia' },
    'M50.1': { description: 'Transtorno de disco cervical com radiculopatia', category: 'Ortopedia' },
    'M51.1': { description: 'Transtornos de discos lombares com radiculopatia (Lombociatalgia)', category: 'Ortopedia' },
    'M54.2': { description: 'Cervicalgia', category: 'Ortopedia' },
    'M54.3': { description: 'Ciatalgia', category: 'Ortopedia' },
    'M54.4': { description: 'Lumbago com ciática', category: 'Ortopedia' },
    'M54.5': { description: 'Dor lombar baixa (Lombalgia)', category: 'Ortopedia' },
    'M54.9': { description: 'Dorsalgia não especificada', category: 'Ortopedia' },
    'M60.9': { description: 'Miosite não especificada (Cãibra / Torcicolo)', category: 'Ortopedia' },
    'M65.3': { description: 'Dedo em gatilho (Tenossinovite estenosante)', category: 'Ortopedia' },
    'M65.4': { description: 'Tenossinovite de De Quervain', category: 'Ortopedia' },
    'M70.2': { description: 'Bursite olecraniana', category: 'Ortopedia' },
    'M71.3': { description: 'Cisto sinovial not specified', category: 'Ortopedia' },
    'M75.1': { description: 'Síndrome do manguito rotador (Ombro doloroso)', category: 'Ortopedia' },
    'M75.5': { description: 'Bursite do ombro', category: 'Ortopedia' },
    'M76.0': { description: 'Tendinite glútea', category: 'Ortopedia' },
    'M76.6': { description: 'Tendinite aquileana (Tendinopatia do Aquiles)', category: 'Ortopedia' },
    'M77.0': { description: 'Epicondilite medial', category: 'Ortopedia' },
    'M77.1': { description: 'Epicondilite lateral (Cotovelo de tenista)', category: 'Ortopedia' },
    'M77.3': { description: 'Esporão calcâneo / Fascite Plantar', category: 'Ortopedia' },
    'M79.3': { description: 'Paniculite não especificada', category: 'Ortopedia' },
    'M79.7': { description: 'Fibromialgia', category: 'Reumatologia' },
    'M92.5': { description: 'Osteocondrose juvenil da tíbia e fíbula (Osgood-Schlatter)', category: 'Ortopedia' },
    'M94.2': { description: 'Condromalácia', category: 'Ortopedia' },
    'R25.2': { description: 'Cãibra e espasmo', category: 'Ortopedia' },
    'S83.6': { description: 'Entorse e distensão de outros ligamentos do joelho', category: 'Ortopedia' },
    'S93.4': { description: 'Entorse e distensão do tornozelo', category: 'Ortopedia' },
    'G57.3': { description: 'Síndrome das pernas inquietas', category: 'Neurologia' },

    // ── Oftalmologia ──
    'H00.0': { description: 'Hordéolo e outras inflamações profundas das pálpebras (Hordéolo/Terçol)', category: 'Oftalmologia' },
    'H00.1': { description: 'Calázio', category: 'Oftalmologia' },
    'H01.0': { description: 'Blefarite', category: 'Oftalmologia' },
    'H04.3': { description: 'Inflamação aguda e não especificada do aparelho lacrimal (Dacrioestenose)', category: 'Oftalmologia' },
    'H10.1': { description: 'Conjuntivite aguda atópica', category: 'Oftalmologia' },
    'H10.9': { description: 'Conjuntivite não especificada (Conjuntivite aguda)', category: 'Oftalmologia' },
    'H11.0': { description: 'Pterígio', category: 'Oftalmologia' },
    'H11.1': { description: 'Degeneração da conjuntiva (Pinguécula)', category: 'Oftalmologia' },
    'H16.0': { description: 'Úlcera de córnea / Ceratite (Queimadura solar ocular)', category: 'Oftalmologia' },
    'H25.9': { description: 'Catarata senil não especificada', category: 'Oftalmologia' },
    'H26.9': { description: 'Catarata não especificada', category: 'Oftalmologia' },
    'H35.3': { description: 'Degeneração macular', category: 'Oftalmologia' },
    'H40.9': { description: 'Glaucoma não especificado', category: 'Oftalmologia' },
    'H43.3': { description: 'Outras opacidades do vítreo (Corpo estranho / Moscas volantes)', category: 'Oftalmologia' },
    'H53.9': { description: 'Defeito visual não especificado (Moscas volantes / Miodesopsias)', category: 'Oftalmologia' },
    'H57.1': { description: 'Dor ocular / Corpo estranho ocular', category: 'Oftalmologia' },
    'H13.1': { description: 'Conjuntivite em doenças infecciosas', category: 'Oftalmologia' },
    'H04.0': { description: 'Dacrioadenite (Dacriocistite)', category: 'Oftalmologia' },
    'H11.3': { description: 'Hemorragia subconjuntival', category: 'Oftalmologia' },
    'H50.9': { description: 'Estrabismo não especificado', category: 'Oftalmologia' },
    'H04.5': { description: 'Estenose e insuficiência do conduto lacrimal (Dacrioestenose)', category: 'Oftalmologia' },
    'H16.1': { description: 'Outras ceratites superficiais sem conjuntivite (Ceratite actínica)', category: 'Oftalmologia' },
    'H20.0': { description: 'Iridociclite aguda e subaguda (Hifema)', category: 'Oftalmologia' },
    'H44.3': { description: 'Outras afecções degenerativas do globo ocular (Hifema traumático)', category: 'Oftalmologia' },
    'H19.3': { description: 'Ceratite e ceratoconjuntivite em outras doenças infecciosas', category: 'Oftalmologia' },
    'H04.4': { description: 'Inflamação crônica do aparelho lacrimal', category: 'Oftalmologia' },

    // ── ORL ──
    'H60.9': { description: 'Otite externa não especificada (Ouvido de nadador)', category: 'ORL' },
    'H61.2': { description: 'Cerume impactado (Rolha de cerume)', category: 'ORL' },
    'H65.9': { description: 'Otite média não supurativa não especificada (OMA)', category: 'ORL' },
    'H66.0': { description: 'Otite média supurativa aguda', category: 'ORL' },
    'H90.3': { description: 'Perda auditiva neurossensorial bilateral (Hipoacusia)', category: 'ORL' },
    'H93.1': { description: 'Zumbido', category: 'ORL' },
    'J34.0': { description: 'Abscesso, furúnculo, carbúnculo do nariz', category: 'ORL' },
    'R04.0': { description: 'Epistaxe (sangramento nasal)', category: 'ORL' },
    'T17.1': { description: 'Corpo estranho na narina', category: 'ORL' },
    'H92.0': { description: 'Otalgia', category: 'ORL' },
    'T16': { description: 'Corpo estranho no ouvido', category: 'ORL' },

    // ── Trauma / Emergência ──
    'R57.0': { description: 'Choque cardiogênico', category: 'Emergência' },
    'S00.0': { description: 'Traumatismo superficial do couro cabeludo', category: 'Trauma' },
    'S05.1': { description: 'Contusão do globo ocular (Hifema traumático)', category: 'Trauma' },
    'S09.9': { description: 'Traumatismo cranioencefálico (TCE) leve', category: 'Trauma' },
    'S60.0': { description: 'Contusão do dedo sem lesão da unha (Hematoma subungueal)', category: 'Trauma' },
    'T14.0': { description: 'Ferida superficial de região NE do corpo', category: 'Trauma' },
    'T20.1': { description: 'Queimadura de primeiro grau da cabeça e pescoço', category: 'Trauma' },
    'T29.1': { description: 'Queimaduras de primeiro grau de múltiplas regiões', category: 'Trauma' },
    'T30.1': { description: 'Queimadura de primeiro grau de local não especificado', category: 'Trauma' },
    'T78.1': { description: 'Outras reações adversas a alimentos (Alergia alimentar)', category: 'Emergência' },
    'T78.2': { description: 'Choque anafilático não especificado (Anafilaxia)', category: 'Emergência' },
    'T78.3': { description: 'Edema angioneurótico (Angioedema)', category: 'Emergência' },
    'T71': { description: 'Asfixia', category: 'Emergência' },
    'T14.1': { description: 'Fratura de local não especificado do corpo', category: 'Trauma' },
    'W57': { description: 'Mordedura ou picada de inseto NE (Picada de inseto)', category: 'Trauma' },
    'W54': { description: 'Mordedura e ataque de cão', category: 'Trauma' },

    // ── Pediatria ──
    'J18.0': { description: 'Pneumonia lobar (PAC pediátrica)', category: 'Pediatria' },
    'J36': { description: 'Abscesso periamigdalino', category: 'Pediatria' },
    'L98.0': { description: 'Granuloma umbilical', category: 'Pediatria' },
    'N98.3': { description: 'Complicações de tentativa de introdução de embrião', category: 'Pediatria' },
    'P59.9': { description: 'Icterícia neonatal não especificada', category: 'Pediatria' },
    'Q38.0': { description: 'Anomalias dos lábios', category: 'Pediatria' },
    'R11': { description: 'Náusea e vômitos (Gastroenterite pediátrica)', category: 'Pediatria' },
    'R57.1': { description: 'Choque hipovolêmico', category: 'Pediatria' },
    'A08.0': { description: 'Enterite por rotavírus (Gastro pediátrica)', category: 'Pediatria' },
    'F98.0': { description: 'Enurese não orgânica', category: 'Pediatria' },
    'B74.3': { description: 'Enterobíase / Oxiuríase (Parasitose intestinal)', category: 'Pediatria' },
    'B77.9': { description: 'Ascaridíase não especificada (Parasitose)', category: 'Pediatria' },
    'A04.9': { description: 'Infecção intestinal bacteriana não especificada', category: 'Pediatria' },

    // ── CID de Procedimentos / Exames ──
    'Z00.0': { description: 'Exame médico geral', category: 'Preventivo' },
    'Z13.6': { description: 'Exame especial de rastreamento de doenças cardiovasculares', category: 'Preventivo' },
    'Z13.8': { description: 'Exame especial de rastreamento de outras doenças', category: 'Preventivo' },
    'Z20.2': { description: 'Contato com e exposição a infecções de transmissão sexual (PEP)', category: 'Preventivo' },
    'Z34.9': { description: 'Supervisão de gravidez normal, não especificada', category: 'Preventivo' },
    'Z85.3': { description: 'História pessoal de neoplasia maligna da mama', category: 'Preventivo' },

    // ── IST / Urologia IST ──
    'A54.0': { description: 'Infecção gonocócica do trato geniturinário inferior (Uretrite)', category: 'Infectologia' },
    'A56.0': { description: 'Infecção por clamídia dos órgãos pélvicos e genitais', category: 'Infectologia' },
    'A63.0': { description: 'Condilomas acuminados (HPV)', category: 'Infectologia' },
    'B20': { description: 'Doença pelo HIV resultando em doenças infecciosas e parasitárias', category: 'Infectologia' },
    'Z21': { description: 'Estado de infecção assintomática pelo HIV (Profilaxia PEP)', category: 'Infectologia' },
};

/**
 * Retorna informações do CID ou um fallback genérico.
 */
export function getCIDInfo(code: string): CIDInfo {
    const clean = code.trim().toUpperCase();
    return CID10_LOOKUP[clean] ?? {
        description: 'Código CID-10',
        category: 'Classificação Internacional de Doenças',
    };
}

/**
 * Retorna true se o código tem descrição no lookup.
 */
export function hasCIDDescription(code: string): boolean {
    return code.trim().toUpperCase() in CID10_LOOKUP;
}

/**
 * Formata lista de CIDs para atestado médico.
 */
export function formatCIDsForAtestado(codes: string[]): string {
    if (codes.length === 0) return '';
    return codes
        .map((code) => {
            const info = getCIDInfo(code);
            return `CID-10: ${code} - ${info.description}`;
        })
        .join('\n');
}
