import React, { useState, memo } from 'react';
import { Lightbulb, AlertTriangle, Target, TrendingUp, Sparkles } from 'lucide-react';

interface PsychologyAISuggestionsProps {
  clientName: string;
  sessionNotes: string;
}

const PsychologyAISuggestions: React.FC<PsychologyAISuggestionsProps> = ({ 
  clientName, 
  sessionNotes 
}) => {
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'insights' | 'goals' | 'risks'>('insights');

  const generateSuggestions = async () => {
    setIsGenerating(true);
    // Simulate AI processing
    await new Promise(resolve => setTimeout(resolve, 1200));
    
    // These would be generated by an AI model in a real implementation
    if (activeTab === 'insights') {
      setSuggestions([
        `Padrão observado: ${clientName} mencionou mais vezes o tema de relacionamentos familiares`,
        `Possível área de melhoria: Autoestima, refletido nas falas sobre autoimagem`,
        `Ponto de atenção: ${clientName} mostrou mais abertura hoje em comparação com sessões anteriores`
      ]);
    } else if (activeTab === 'goals') {
      setSuggestions([
        `Meta recomendada: Explorar sentimentos de ansiedade em situações sociais`,
        `Nova direção: Trabalhar aspectos de assertividade`,
        `Ajuste sugerido: Revisar metas de curto prazo estabelecidas na 3ª sessão`
      ]);
    } else {
      setSuggestions([
        `Risco baixo identificado: ${clientName} demonstra bom suporte social`,
        `Ponto de atenção: Monitorar evolução de sintomas de ansiedade`,
        `Acompanhamento necessário: Avaliação de risco será revisitada na próxima sessão`
      ]);
    }
    
    setIsGenerating(false);
  };

  const suggestionIcons = {
    insights: Lightbulb,
    goals: Target,
    risks: AlertTriangle
  };

  const tabs = [
    { id: 'insights', label: 'Insights', icon: Lightbulb },
    { id: 'goals', label: 'Metas', icon: Target },
    { id: 'risks', label: 'Riscos', icon: AlertTriangle }
  ];

  return (
    <div className="bg-white rounded-lg p-5 border border-gray-200 shadow-sm">
      <div className="flex justify-between items-center mb-4">
        <h3 className="font-bold text-gray-800 text-lg flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-purple-500" />
          Sugestões da IA
        </h3>
        <span className="text-xs bg-purple-100 text-purple-800 px-2 py-1 rounded-full">
          Assistiva
        </span>
      </div>

      <div className="flex gap-1 mb-4 border-b border-gray-200">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id as any);
                setSuggestions([]); // Reset suggestions when changing tabs
              }}
              className={`px-3 py-1.5 text-sm rounded-t-lg flex items-center gap-2 ${
                activeTab === tab.id
                  ? 'bg-purple-100 text-purple-800 border-b-2 border-purple-500'
                  : 'text-gray-600 hover:bg-gray-100'
              }`}
            >
              <Icon className="w-4 h-4" />
              {tab.label}
            </button>
          );
        })}
      </div>

      <button
        onClick={generateSuggestions}
        disabled={isGenerating}
        className="w-full flex items-center justify-center gap-2 bg-purple-100 text-purple-700 px-4 py-2 rounded-lg hover:bg-purple-200 disabled:opacity-50 mb-4"
      >
        {isGenerating ? (
          <>
            <Sparkles className="w-4 h-4 animate-spin" />
            Processando...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            Gerar Sugestões de {tabs.find(t => t.id === activeTab)?.label}
          </>
        )}
      </button>

      {suggestions.length > 0 ? (
        <div className="space-y-3">
          <h4 className="font-semibold text-gray-700 flex items-center gap-2">
            {React.createElement(suggestionIcons[activeTab], { className: "w-4 h-4" })}
            Sugestões para {clientName}
          </h4>
          <ul className="space-y-2">
            {suggestions.map((suggestion, index) => (
              <li 
                key={index} 
                className="p-3 bg-blue-50 rounded-lg border border-blue-100 text-sm text-gray-700 flex items-start gap-2"
              >
                <div className="w-1.5 h-1.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0"></div>
                {suggestion}
              </li>
            ))}
          </ul>
          <div className="mt-3 pt-3 border-t border-gray-200 text-xs text-gray-500">
            <p>Lembrete: As sugestões da IA são apenas apoio à prática clínica.</p>
            <p>O psicólogo deve sempre revisar e validar todas as recomendações.</p>
          </div>
        </div>
      ) : (
        <div className="text-center py-6 text-gray-500">
          <Lightbulb className="w-8 h-8 mx-auto text-gray-300 mb-2" />
          <p>Clique em "Gerar Sugestões" para obter recomendações baseadas na sessão</p>
          <p className="text-xs mt-2">A IA analisará os dados e fornecerá insights relevantes</p>
        </div>
      )}
    </div>
  );
};

export default memo(PsychologyAISuggestions);